### ISSUE TITLE
CopyRecord only 1 level deep

### ISSUE THREAD

**Issue by kdsudac** [chainreactionmfg/mutablerecords#10]
Docstring for CopyRecord has this "like a Record-only deepcopy."  Ambiguous what a Record-only deepcopy is.  In actuality it only copies one extra level deep so any mutable nested data structures will still be shared between the original and the copy.

Looks like __deepcopy__ is implemented on RecordClass and does a true deepcopy.

Maybe just clean up the docstring of this function and refer users to deepcopy if they want a true deepcopy.

**Comment by fahhem** [comment]
It means that it will recurse into any `Record`s, but not into other objects. What wording do you recommend?

**Comment by kdsudac** [comment]
Created https://github.com/chainreactionmfg/mutablerecords/pull/11 with suggestion.
