### ISSUE TITLE
Way to simply subclass a RecordClass?

### ISSUE THREAD

**Issue by kdsudac** [chainreactionmfg/mutablerecords#12]
This might be a dumb question, but is there a way to subclass a RecordClass without using the Record function?

i.e. I know you can inline like this:
```
class MyRecod(mutablerecords.Record('MyRecord')):
    required_attributes = ['req1']
    optional_attributes = {'opt1': None}
```

Is there any way to do this without having the inline mutablerecords.Record call?

Something like:
```
class MyRecod(mutablerecords.RecordClass):
    required_attributes = ['req1']
    optional_attributes = {'opt1': None}
```

I'm not sure what I'd be missing the RecordMeta class.

**Comment by fahhem** [comment]
The metaclass is necessary to handle things when someone else subclasses your class, or to handle comparing or hashing types correctly (not instances). Why do you want to avoid the `Record` call, to avoid the extra name? Just repeat the name of the subclass, the name is used to enable pickling/unpickling

**Comment by kdsudac** [comment]
The main reason I'd like to avoid it, is it appears to confuse some code search/analysis tools we use at google.  In the example above, any methods on MyRecord that are added would not be recognized as methods but would appear as module level functions.

The other reasons is the inlining can get a bit ugly.   Example from openhtf:
```
class PhaseRecord(  # pylint: disable=no-init
    mutablerecords.Record(
        'PhaseRecord', ['descriptor_id', 'name', 'codeinfo'],
        {'measurements': None, 'options': None,
         'start_time_millis': int, 'end_time_millis': None,
         'attachments': dict, 'result': None, 'outcome': None})):
```

Which admittedly we can clean up on our own:
```
class PhaseRecord(mutablerecords.Record('PhaseRecord'):
  required_attributes =  ['descriptor_id', 'name', 'codeinfo']
  optional_attributes = {
      'measurements': None, 
      'options': None,
      'start_time_millis': int,
      'end_time_millis': None,
      'attachments': dict,
      'result': None,
      'outcome': None
  }
```

**Comment by fahhem** [comment]
The methods show up on the module level? That seems like broken tools, report a bug, because they're open sourcing that system right now as Kythe. It's still a class, no matter what the base class is, so the methods should show up correctly.

**Comment by fahhem** [comment]
Since this is a failure of the tools (it's a `class` by all accounts, even statically), I'm going to close this.
