### ISSUE TITLE
Feature Request: Ability to pass updated field values to CopyRecord.

### ISSUE THREAD

**Issue by grybmadsci** [chainreactionmfg/mutablerecords#6]
I have a case where I do some special handling on creation of a Record in `__new__`, but it's not playing nice with `CopyRecord`.  I've ended up overriding `__setattr__` to accomplish what I need, but it would be a lot cleaner on my end if i could `mutablerecords.CopyRecord(original, field_name='new_value')`

**Comment by grybmadsci** [comment]
Actually, because you're invoking `object.__setattr__` in `RecordClass`, even overriding `__setattr__` doesn't work.  I was able to do what I needed by overriding **init** instead, but it would still be handy to be able to just do the update in the call to `CopyRecord`, if you think that doesn't break the convention of `CopyRecord` too much.

**Comment by fahhem** [comment]
Are you taking different values than the fields in your `__new__`? That's bitten me in the past and I've typically been able to switch to a `@classmethod` for some use-cases and others I just renamed the argument. Most of my use-cases of `CopyRecord` is to override a field or two, and I can't think of a better name for "copy-and-replace" so I'd be fine adding that functionality to `CopyRecord`.

**Comment by grybmadsci** [comment]
i'm actually auto-filling one of the fields conditionally based on one that is passed in, and there were some weird nuances around it, the CopyRecord update just lets me skip some shenanigans.  Thanks!

**Comment by fahhem** [comment]
Sounds like you want an `@property` rather than a separate field?
