### ISSUE TITLE
Parameter order is mixed up with inheritance

### ISSUE THREAD

**Issue by arsharma1** [chainreactionmfg/mutablerecords#9]
The order of parameters with inherited mutablerecords puts the new required attributes first.  This is contrary to the documentation in README.md.

`import mutablerecords`
`A = mutablerecords.Record('A', ['a', 'b'])`
`class B(A): required_attributes = ['c']`

`foo = B(1, 2, 3)`
`print foo`
`# B(c=1, a=2, b=3)`

**Comment by fahhem** [comment]
Ah-ha, you're not up-to-date. I spent so much time re-reading that code and I just checked the git history and it says:

2016/08/12 "Ensure subclass's required_attributes are after base classes"
2016/08/12 "Update version to 0.4.1 for new required_attributes bugfix"

And PyPI shows that I uploaded 0.4.1 that same day. In a fresh virtualenv I run your example and get this:

```py
B(a=1, b=2, c=3)
```
